#Pandas

###Install Pandas

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

###Import Pandas

In [2]:
import pandas as pd

pd.__version__

'2.2.3'

#***Pandas Series***

In [15]:
# creating series
series = pd.Series([10,2,3,5,8,0,3,2,5])

print(series)

0    10
1     2
2     3
3     5
4     8
5     0
6     3
7     2
8     5
dtype: int64

In [11]:
#indexing
print(series[1])

2

###Slicing

In [14]:
print(series[2:7:2])

2    3
4    8
6    3
dtype: int64

#Attributes

1. index : The index attribute returns the labels used to identify each element in a Series.

In [17]:
series.index

RangeIndex(start=0, stop=9, step=1)

2. values : The values attribute returns the actual data stored in a Series as an array.

In [18]:
series.values

array([10,  2,  3,  5,  8,  0,  3,  2,  5])

3. dtype : The dtype attribute tells us the data type of the values stored in a Series

In [19]:
series.dtype

dtype('int64')

#Methods

In [20]:

sales = pd.Series([500, 200, 800, None, 400, 900])
print(sales)

0    500.0
1    200.0
2    800.0
3      NaN
4    400.0
5    900.0
dtype: float64

###1. sales.head()
Returns the first 5 elements of a Series by default.

In [22]:
sales.head()

0    500.0
1    200.0
2    800.0
3      NaN
4    400.0
dtype: float64

In [24]:
sales.head(6)

0    500.0
1    200.0
2    800.0
3      NaN
4    400.0
5    900.0
dtype: float64

###sales.tail()
 Returns the last five elements of a Series by default.

In [25]:
sales.tail(3)

3      NaN
4    400.0
5    900.0
dtype: float64

###sort_values()
Sorts the values in a Series in ascending or descending order.

In [27]:
sales.sort_values()

1    200.0
4    400.0
0    500.0
2    800.0
5    900.0
3      NaN
dtype: float64

series.sort_values(
    ascending=True,
    na_position="last"
)

na_position="last": Places missing values at the end by default.
na_position="first" → NaN at the start.

In [29]:
sales.sort_values(na_position = "first")

3      NaN
1    200.0
4    400.0
0    500.0
2    800.0
5    900.0
dtype: float64

4. count()
Returns the number of non-missing values in a Series.

len(sales) counts all elements, including missing ones.

In [31]:
print(sales.count())

5

isnull()
Checks each element to determine whether it is missing (NaN or another recognized missing value). Returns True for missing values and False otherwise.

In [32]:
print(sales.isnull())

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

#Operations

In [33]:
print(sales + 1)

0    501.0
1    201.0
2    801.0
3      NaN
4    401.0
5    901.0
dtype: float64

In [34]:
print(sales * 5)

0    2500.0
1    1000.0
2    4000.0
3       NaN
4    2000.0
5    4500.0
dtype: float64

In [35]:
print(sales**2)

0    250000.0
1     40000.0
2    640000.0
3         NaN
4    160000.0
5    810000.0
dtype: float64

#Missing Values

In [36]:

sales_with_missing = pd.Series([2, None, 5])

print(sales_with_missing)

0    2.0
1    NaN
2    5.0
dtype: float64

In [37]:
sales_with_missing.isnull()

0    False
1     True
2    False
dtype: bool

fillna(value)


Replaces missing values with the value you specify.

series.fillna(value)

In [38]:
print(sales_with_missing.fillna(0))

0    2.0
1    0.0
2    5.0
dtype: float64

By default, fillna() returns a new Series and does not modify the original Series.

To update the original variable, assign the result back:

In [39]:
sales_with_missing = sales_with_missing.fillna(0)

In [40]:
sales_with_missing

0    2.0
1    0.0
2    5.0
dtype: float64