#Pandas DataFrames

A DataFrame is a two-dimensional data structure in Pandas that stores data in rows and columns

In [1]:
import pandas as pd

In [2]:
# create data frame

# pd.DataFrame({'column_name': [values]})

data = pd.DataFrame({
    'Name': ['Anna', 'Ben'],
    'Lemonades': [2, 3]
})

print(data)

   Name  Lemonades
0  Anna          2
1   Ben          3

In [4]:

s1 = pd.Series(data=[1, 2, 3, 4, 5])

print(s1)

print()

s2 = pd.Series(data=[10, 20, 30, 40, 50])

print(s2)

0    1
1    2
2    3
3    4
4    5
dtype: int64

0    10
1    20
2    30
3    40
4    50
dtype: int64

Creating a Series with custom index labels

In [5]:
si = pd.Series(
    data=[100, 200, 300, 400, 500],
    index=list('abcde')
)

print(si)

a    100
b    200
c    300
d    400
e    500
dtype: int64

Creating a DataFrame from two Series

In [6]:
data = pd.DataFrame({
    'C1': s1,
    'C2': s2
})

print(data)

#'C1': s1 creates the first column named C1.
#'C2': s2 creates the second column named C2.
#Pandas aligns the Series using their index labels.

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

#Attributes

In [10]:
# shape

s1.shape

(5,)

In [11]:
data.shape

(5, 2)

In [12]:
#columns

data.columns

Index(['C1', 'C2'], dtype='object')

In [13]:
#dtype

data.dtypes

C1    int64
C2    int64
dtype: object

#Accessing data in Dataframe

loc[] → Access data using row and column labels.



iloc[] → Access data using integer positions.

In [14]:
# data.loc[row_label, column_label]

print(data.loc[1, 'C1'])

2

In [15]:
# data.iloc[row_position, column_position]

print(data.iloc[1, 0])

2

#Methods

In [19]:

data.head(2)

   C1  C2
0   1  10
1   2  20

In [22]:
data.sort_values(by='C1')                 # Ascending order

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [23]:

data.sort_values(by='C1', ascending=False) # Descending order

   C1  C2
4   5  50
3   4  40
2   3  30
1   2  20
0   1  10

In [24]:
data.tail(2)

   C1  C2
3   4  40
4   5  50

In [25]:
data.describe()

             C1         C2
count  5.000000   5.000000
mean   3.000000  30.000000
std    1.581139  15.811388
min    1.000000  10.000000
25%    2.000000  20.000000
50%    3.000000  30.000000
75%    4.000000  40.000000
max    5.000000  50.000000

In [26]:
data.info

<bound method DataFrame.info of    C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50>

In [34]:
data.count(axis=1)
#horizontal in each row

0    2
1    2
2    2
3    2
4    2
dtype: int64

In [35]:
#in column
data.count(axis=0)

C1    5
C2    5
dtype: int64

In [30]:
data.isnull()

      C1     C2
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False

#Filter

In [37]:
data[data['C1'] >=2]

   C1  C2
1   2  20
2   3  30
3   4  40
4   5  50

# Adding a column

In [60]:
data['Tips'] = [1, 2,3,4,5]

data

   C1  C2  Tips
0   1  10     1
1  25  25     2
2  23  22     3
3   4  40     4
4   5  50     5

# Updating a value


- data[C1] selects the column whose name is the C1.
- data[C1] == 25 finds rows where that column's value is 25.
- data.loc[condition, 'C1'] = 19 updates the C1 value in those rows to 19.

In [51]:
data

   C1  C2  Tips     1
0   1  10     1   NaN
1  25  25    25  19.0
2   3  30     3   NaN
3   4  40     4   NaN
4   5  50     5   NaN

In [52]:
data.loc[data['C1'] == 3] = 22

data

   C1  C2  Tips     1
0   1  10     1   NaN
1  25  25    25  19.0
2  22  22    22  22.0
3   4  40     4   NaN
4   5  50     5   NaN

In [54]:
data.loc[data['C1'] == 22,'C1'] = 23

data

   C1  C2  Tips     1
0   1  10     1   NaN
1  25  25    25  19.0
2  23  22    22  22.0
3   4  40     4   NaN
4   5  50     5   NaN

#Renaming

In [55]:
data.rename(columns = {'C1' : 'Column1'} )

   Column1  C2  Tips     1
0        1  10     1   NaN
1       25  25    25  19.0
2       23  22    22  22.0
3        4  40     4   NaN
4        5  50     5   NaN

#Deleting a column using del

In [56]:
del data[1]

In [57]:
data

   C1  C2  Tips
0   1  10     1
1  25  25    25
2  23  22    22
3   4  40     4
4   5  50     5

#Deleting a column using drop

In [62]:
data.drop(columns = {'Tips'} , inplace = True)

In [63]:
data

   C1  C2
0   1  10
1  25  25
2  23  22
3   4  40
4   5  50