#Indexing and Selection

###1. data.set_index('Name', inplace=True)

set_index() is used to make an existing column the index (row label) of a DataFrame instead of using the default numbers like 0, 1, 2

In [9]:
import pandas as pd

s1 = pd.Series(data=[1,2,3,4,56])
s2 = pd.Series(data=[8,9,5,4,3])

data = pd.DataFrame({
    'C1': s1,
    'C2': s2
    })

data.set_index('C1' , inplace=True)
print(data)

    C2
C1
1    8
2    9
3    5
4    4
56   3

###2. reset_index()


reset_index() is used to bring the existing index back to a normal column and create a new default index (0, 1, 2, ...).

In [12]:
data.reset_index(inplace=True)
print(data)

   C1  C2
0   1   8
1   2   9
2   3   5
3   4   4
4  56   3

###3. MultiIndex

A MultiIndex means a DataFrame has more than one index level. Instead of using only one column as the row label, we use two or more columns together.

In [13]:
multi_data = pd.DataFrame({
    'Park': ['A', 'A', 'B', 'B'],
    'Name': ['Anna', 'Ben', 'Chris', 'Daisy'],
    'Lemonades': [2, 3, 4, 5]
}).set_index(['Park', 'Name'])

print(multi_data)

            Lemonades
Park Name
A    Anna           2
     Ben            3
B    Chris          4
     Daisy          5

###4. Selecting with Conditions

 means filtering rows based on a rule.

In [14]:
multi_data[multi_data['Lemonades'] >= 3]

            Lemonades
Park Name
A    Ben            3
B    Chris          4
     Daisy          5

###5. Query Method — query()


The query() method filters rows using a condition written as a string.

In [18]:
multi_data.query('Lemonades >= 3')

            Lemonades
Park Name
A    Ben            3
B    Chris          4
     Daisy          5

#Working with Data

###1. Saving a dataframe to csv

In [19]:
multi_data.to_csv('lemonade_sales.csv')

In [20]:
data1 = pd.read_csv('lemonade_sales.csv')
print(data1)

  Park   Name  Lemonades
0    A   Anna          2
1    A    Ben          3
2    B  Chris          4
3    B  Daisy          5

###2. Creating a DataFrame from a Dictionary

In [21]:
import numpy as np
dictt = {
    'x': [1, 2, 3],
    'y': np.array([10, 20, 30]),
    'z': 50
}

pd.DataFrame(dictt)

   x   y   z
0  1  10  50
1  2  20  50
2  3  30  50

###3. Creating a DataFrame from a List


 A list of lists can be converted into a DataFrame, where each inner list represents one row.

In [2]:
import pandas as pd
listt = [
    [1, 2, 100],
    [2, 4, 100],
    [3, 8, 100]
]

pd.DataFrame(listt, columns=['x', 'y', 'z'])

   x  y    z
0  1  2  100
1  2  4  100
2  3  8  100

In [3]:
print(listt)

[[1, 2, 100], [2, 4, 100], [3, 8, 100]]

###4. Creating a DataFrame from a numpy array

In [4]:
import numpy as np

arr = np.array([
    [ 1,2,100],
    [ 2,4,100],
    [ 3,8,100]
])

pd.DataFrame(arr, columns=['x', 'y', 'z'])

   x  y    z
0  1  2  100
1  2  4  100
2  3  8  100