#Data Cleaning and Preprocessing

###1. Handling missing data


1. dropna() does not modify the original DataFrame by default. To save the change:

In [1]:
import pandas as pd

In [15]:
saless = pd.Series([2,4,6,None,3,None,3])

saless.dropna()

0    2.0
1    4.0
2    6.0
4    3.0
6    3.0
dtype: float64

2. .fillna(0)

Replaces missing values with a specified value. Here, 0 is used.

In [17]:
saless.fillna(0,inplace = True)

In [18]:
saless

0    2.0
1    4.0
2    6.0
3    0.0
4    3.0
5    0.0
6    3.0
dtype: float64

* Fill witth mean

In [19]:
saless.mean()

np.float64(2.5714285714285716)

In [21]:
saless.fillna(saless.mean(),inplace = True)

In [22]:
saless

0    2.0
1    4.0
2    6.0
3    0.0
4    3.0
5    0.0
6    3.0
dtype: float64

#Removing Duplicates


drop_duplicates() removes duplicate rows from a DataFrame, keeping the first occurrence by default.

In [23]:
data = pd.DataFrame({
    'C1': ['Anna', 'Ben', 'Anna', 'Raj'],
    'C2': [2, 3, 2, 5]
})

In [24]:
data.drop_duplicates()

     C1  C2
0  Anna   2
1   Ben   3
3   Raj   5

In [25]:
data

     C1  C2
0  Anna   2
1   Ben   3
2  Anna   2
3   Raj   5

###Replacing Duplicates

In [26]:
data.replace(2,900)

     C1   C2
0  Anna  900
1   Ben    3
2  Anna  900
3   Raj    5

In [27]:
data

     C1  C2
0  Anna   2
1   Ben   3
2  Anna   2
3   Raj   5

#Type Conversion

astype()

converts a column or Series into a specified data type.

In [30]:
data['C2'] = data['C2'].astype(float)

In [31]:
data

     C1   C2
0  Anna  2.0
1   Ben  3.0
2  Anna  2.0
3   Raj  5.0

#String Operation

In [32]:
data['C1'].str.upper()

0    ANNA
1     BEN
2    ANNA
3     RAJ
Name: C1, dtype: object

In [33]:
data

     C1   C2
0  Anna  2.0
1   Ben  3.0
2  Anna  2.0
3   Raj  5.0