#Data aggregation and grouping

In [1]:
import pandas as pd

In [3]:
import pandas as pd

data = pd.DataFrame({
    'Name': ['Anna', 'Ben', 'Anna', 'Ben', 'Chris'],
    'Lemonades': [2, 3, 4, 5, 6]
})

print(data)

    Name  Lemonades
0   Anna          2
1    Ben          3
2   Anna          4
3    Ben          5
4  Chris          6

#1. groupby()

groups rows that have the same value in a specified column.

In [4]:
grouped = data.groupby('Name')

In [12]:
data = grouped

In [13]:
print(data)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x784343f4df90>

In [9]:
grouped.sum()

       Lemonades
Name
Anna           6
Ben            8
Chris          6

#Aggregation

In [5]:
#1
grouped['Lemonades'].mean()

Name
Anna     3.0
Ben      4.0
Chris    6.0
Name: Lemonades, dtype: float64

In [6]:
#2
grouped['Lemonades'].min()

Name
Anna     2
Ben      3
Chris    6
Name: Lemonades, dtype: int64

In [8]:
#It returns the largest value in each group.
grouped['Lemonades'].max()

Name
Anna     4
Ben      5
Chris    6
Name: Lemonades, dtype: int64

#pivot_table()

 A pivot table summarizes data by grouping it using selected rows and columns and applying an aggregation function.

In [10]:
data.pivot_table(values='Lemonades', index='Name')

       Lemonades
Name
Anna         3.0
Ben          4.0
Chris        6.0

In [13]:
data.pivot_table(
    values='Lemonades',
    index='Name',
    aggfunc=['sum','mean']
)

            sum      mean
      Lemonades Lemonades
Name
Anna          6       3.0
Ben           8       4.0
Chris         6       6.0

#pd.crosstab()

 pd.crosstab() creates a frequency table showing how often combinations of values occur.

In [16]:
pd.crosstab(data['Name'], data['Lemonades'])

Lemonades  2  3  4  5  6
Name
Anna       1  0  1  0  0
Ben        0  1  0  1  0
Chris      0  0  0  0  1

In [17]:
import pandas as pd

data2 = pd.DataFrame({
    'Name': ['Anna', 'Ben', 'Chris', 'Ben', 'Chris'],
    'Lemonades': [12, 13, 4, 25, 96]
})

In [18]:
data2

    Name  Lemonades
0   Anna         12
1    Ben         13
2  Chris          4
3    Ben         25
4  Chris         96

***Concatenation***

Concatenation combines DataFrames by stacking them vertically (rows) or horizontally (columns).

In [19]:
result = pd.concat([data,data2])

In [20]:
result

    Name  Lemonades
0   Anna          2
1    Ben          3
2   Anna          4
3    Ben          5
4  Chris          6
0   Anna         12
1    Ben         13
2  Chris          4
3    Ben         25
4  Chris         96

In [21]:
#to create a fressh index:

result2 = pd.concat([data,data2], ignore_index=True)

In [22]:
result2

    Name  Lemonades
0   Anna          2
1    Ben          3
2   Anna          4
3    Ben          5
4  Chris          6
5   Anna         12
6    Ben         13
7  Chris          4
8    Ben         25
9  Chris         96

In [23]:
#horizontally
pd.concat([data,data2], axis=1)

    Name  Lemonades   Name  Lemonades
0   Anna          2   Anna         12
1    Ben          3    Ben         13
2   Anna          4  Chris          4
3    Ben          5    Ben         25
4  Chris          6  Chris         96

***merge()***

it uses a inner join

Merging combines DataFrames by matching values in a common column or columns, similar to SQL joins.

In [25]:

pd.merge(data, data2, on='Name')

    Name  Lemonades_x  Lemonades_y
0   Anna            2           12
1    Ben            3           13
2    Ben            3           25
3   Anna            4           12
4    Ben            5           13
5    Ben            5           25
6  Chris            6            4
7  Chris            6           96

In [26]:
#change join type
pd.merge(data, data2, on='Name', how='inner')
pd.merge(data, data2, on='Name', how='left')
pd.merge(data, data2, on='Name', how='right')
pd.merge(data, data2, on='Name', how='outer')

    Name  Lemonades_x  Lemonades_y
0   Anna            2           12
1   Anna            4           12
2    Ben            3           13
3    Ben            3           25
4    Ben            5           13
5    Ben            5           25
6  Chris            6            4
7  Chris            6           96

***join(): joining on index***


combines DataFrames using their indexes by default. It is useful when the matching information is stored in row labels rather than regular columns.

In [27]:
data1 = pd.DataFrame({
    'City': ['Pune', 'Mumbai', 'Delhi']
}, index=['Anna', 'Ben', 'Chris'])

data2 = pd.DataFrame({
    'Lemonades': [2, 3, 4]
}, index=['Anna', 'Ben', 'Chris'])

result = data1.join(data2)
print(result)

         City  Lemonades
Anna     Pune          2
Ben    Mumbai          3
Chris   Delhi          4