#Working with Time Series

In [1]:
import pandas as pd

data = pd.DataFrame({
    'Date': [
        '2025-04-28',
        '2025-04-29',
        '2025-04-30',
        '2025-05-01',
        '2025-05-02'
    ],
    'Lemonades': [10, 20, 15, 25, 30]
})

print(data)

         Date  Lemonades
0  2025-04-28         10
1  2025-04-29         20
2  2025-04-30         15
3  2025-05-01         25
4  2025-05-02         30

#DateTime Index


A DateTime index means using a date column as the DataFrame's index. This makes it easier to select, filter, and summarize data by date.

In [2]:
#This converts date strings into Pandas datetime values so Pandas can recognize and process them as dates.
data['Date'] = pd.to_datetime(data['Date'])

#Set the date as the index.
data.set_index('Date', inplace=True)

In [3]:
data

            Lemonades
Date
2025-04-28         10
2025-04-29         20
2025-04-30         15
2025-05-01         25
2025-05-02         30

#Converting Strings to Date

In [4]:
pd.to_datetime('2025-04-29')

Timestamp('2025-04-29 00:00:00')

In [ ]:
#entire clumn

data['Date'] = pd.to_datetime(data['Date'])

#Resampling

groups time-based data into a different time frequency, such as daily, weekly, monthly, or yearly, and lets you calculate summaries for each period.

In [7]:
data.resample('W').sum()

            Lemonades
Date
2025-05-04        100

In [8]:
data.resample('M').sum()

/tmp/ipykernel_1885/2215768663.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  data.resample('M').sum()

            Lemonades
Date
2025-04-30         45
2025-05-31         55


'D'	Daily

'W'	Weekly

'MS'	Month start

'ME'	Month end

'QE'	Quarter end

'YE'	Year end

'A'   Annual

#Shifting / Lagging

shift() moves values up or down by a specified number of rows. It is often used to compare the current value with a previous value.

In [9]:
data['Previous Lemonades'] = data['Lemonades'].shift(1)

In [10]:
data

            Lemonades  Previous Lemonades
Date
2025-04-28         10                 NaN
2025-04-29         20                10.0
2025-04-30         15                20.0
2025-05-01         25                15.0
2025-05-02         30                25.0

#Rolling Calculations — rolling()

rolling() calculates a statistic over a moving window of rows, such as a rolling average over the last two observations.

In [11]:
data['Rolling Average'] = (
    data['Lemonades'].rolling(window=2).mean()
)

#rolling(window=2) considers two consecutive values at a time.
#.mean() calculates their average.
#The window moves forward one row at a time.

In [12]:
data

            Lemonades  Previous Lemonades  Rolling Average
Date
2025-04-28         10                 NaN              NaN
2025-04-29         20                10.0             15.0
2025-04-30         15                20.0             17.5
2025-05-01         25                15.0             20.0
2025-05-02         30                25.0             27.5